### ISSUE TITLE
How to run only the Phylogeny tree contruction whitout GEMOMA_ann?

### ISSUE THREAD

**Issue by BenAawf** [mag-wolf/GEMOMA-to-Phylogeny#1]
Dear @mag-wolf ,

I hope this message finds you well. I would like to express my gratitude for your valuable work and support provided on this platform.

I have recently attempted to ascertain genomic relationships through the construction of a phylogenetic tree using your mediated shared SCOS method. In this endeavor, I have compiled 13 bird genome assemblies relevant to my species of interest, in addition to the human genome (GRCH38). Following your guidelines, I successfully completed the analysis without encountering any errors. Subsequently, I employed iTOL to visualize the tree file "FcC_supermatrix_trimmed.fas.treefile" obtained from the "SUPERMATRIX2" folder.

However, the results appear to deviate from my expectations, as I anticipated that the human genome would be treated as an outgroup. 

I kindly request your assistance in evaluating the attached file [https://drive.google.com/file/d/15UiadBNztV8dbYH89VsNJk9en4F2DnZS/view?usp=share_link](url) and providing any necessary guidance to address this issue.

On the other hand, since I have the proteomics data for each species, How can I skip the annotation step? It took me a week to finish the run on a workstation with 48 CPUs and 1TB. I tried to deactivate it by passing the cmd "rungemoma=FALSE." But got an error in the rest cmd

kind regards
ben

**Comment by mag-wolf** [comment]
Hi Ben, 

it seems I can't open the tree file. Could you provide it via another platform? 

For now, I can only speculate and would like to emphasize two things. 

1.) A tree constructed with this pipeline is always unrooted, given that every phylogentic reconstruction would be trumendesly more complex if we want to assess which of the species you included is the best fitted outgroup. Frankly, nobody does this. BUT, what you can do it load this tree to e.g. iTOL and click on the branch of the human leaf. Then, a menu should open that allows you to specify this branch retroperspective as the outgroup. This is kind of the normal approach to do so. 

2.) My pipeline is a bit lazy. Meaning that you can't specify anything via command line. You need to open the source code with
for exemple "nano" and make changes in the user-section in the beginning. There you can specify a lot of things, including filter
criteria, computational ressources or which part of the pipeline you would like to run. So this would be my first adress to find issues. 

I hope this already helps,

Cheers,

Magnus

**Comment by BenAawf** [comment]
kindly try : this https://drive.google.com/file/d/15UiadBNztV8dbYH89VsNJk9en4F2DnZS/view?usp=sharing

**Comment by mag-wolf** [comment]
Hi Ben, 

it really seems like I suspected, that IQTREE just defined a random taxon as root and that you can fix this by simply defining a root yourself in e.g. ITOL. Could you try this?

Cheers,

Magnus

**Comment by BenAawf** [comment]
Hi @mag-wolf 
Thank you for your prompt response. Your suggestion regarding iTOL was very helpful.

I am interested in including the divergence time from the TimeTree database in my analysis, similar to the approach taken in figure 3 of this article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8985102/. Could you please provide guidance on how to accomplish this or suggest any other tools that may be useful?

Thank you for your assistance and time.
ben

**Comment by mag-wolf** [comment]
Hi Ben, 

IQTree or MCMC2 would be my first ideas to look at. Here the tutorial for IQTREE: http://www.iqtree.org/doc/Dating 
You just need to gather as many (minimal) calibration points from fossil records as possible. 

As a site note, if you constructed a dated tree, iTOL performs poor in visualizing this. There I would use FigTree. 

Cheers,

Magnus
